//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapp.AppBase.Std.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DbMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grapp.AppBase.Std.Library.Properties.DbMessages", typeof(DbMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificados válidos:.
        /// </summary>
        public static string Certificate_ShowSelectionUIFromValidCertificates_Certificados_válidos_ {
            get {
                return ResourceManager.GetString("Certificate_ShowSelectionUIFromValidCertificates_Certificados_válidos_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o certificado que deseja utilizar.
        /// </summary>
        public static string Certificate_ShowSelectionUIFromValidCertificates_Selecione_o_certificado_que_deseja_utilizar {
            get {
                return ResourceManager.GetString("Certificate_ShowSelectionUIFromValidCertificates_Selecione_o_certificado_que_dese" +
                        "ja_utilizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione os certificados que deseja utilizar.
        /// </summary>
        public static string Certificate_ShowSelectionUIFromValidCertificates_Selecione_os_certificados_que_deseja_utilizar {
            get {
                return ResourceManager.GetString("Certificate_ShowSelectionUIFromValidCertificates_Selecione_os_certificados_que_de" +
                        "seja_utilizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hora(s) {1} minuto(s) e {2} segundo(s).
        /// </summary>
        public static string Date_Format1 {
            get {
                return ResourceManager.GetString("Date_Format1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hora(s) e {1} minuto(s).
        /// </summary>
        public static string Date_Format2 {
            get {
                return ResourceManager.GetString("Date_Format2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hora(s) e {1} segundo(s).
        /// </summary>
        public static string Date_Format3 {
            get {
                return ResourceManager.GetString("Date_Format3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hora(s).
        /// </summary>
        public static string Date_Format4 {
            get {
                return ResourceManager.GetString("Date_Format4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minuto(s) e {1} segundo(s).
        /// </summary>
        public static string Date_Format5 {
            get {
                return ResourceManager.GetString("Date_Format5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minuto(s).
        /// </summary>
        public static string Date_Format6 {
            get {
                return ResourceManager.GetString("Date_Format6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} segundo(s).
        /// </summary>
        public static string Date_Format7 {
            get {
                return ResourceManager.GetString("Date_Format7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Não Definido].
        /// </summary>
        public static string DateRange_ToString__Não_Definido_ {
            get {
                return ResourceManager.GetString("DateRange_ToString__Não_Definido_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maior ou igual {0} e menor ou gual {1}.
        /// </summary>
        public static string DateRange_ToString_maior_ou_igual__0__e_menor_ou_gual__1_ {
            get {
                return ResourceManager.GetString("DateRange_ToString_maior_ou_igual__0__e_menor_ou_gual__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maior ou igual a {0}.
        /// </summary>
        public static string DateRange_ToString_maior_ou_igual_a__0_ {
            get {
                return ResourceManager.GetString("DateRange_ToString_maior_ou_igual_a__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menor ou igual a {0}.
        /// </summary>
        public static string DateRange_ToString_menor_ou_igual_a__0_ {
            get {
                return ResourceManager.GetString("DateRange_ToString_menor_ou_igual_a__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 metro.
        /// </summary>
        public static string Geo_FormatDistance_ZeroMeter {
            get {
                return ResourceManager.GetString("Geo_FormatDistance_ZeroMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período informado está incompleto..
        /// </summary>
        public static string XDateRangeAttribute_IsValid_O_período_informado_está_incompleto_ {
            get {
                return ResourceManager.GetString("XDateRangeAttribute_IsValid_O_período_informado_está_incompleto_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período máximo deve ser de {0} dia(s)..
        /// </summary>
        public static string XDateRangeAttribute_IsValid_O_período_máximo_deve_ser_de__0__dia_s__ {
            get {
                return ResourceManager.GetString("XDateRangeAttribute_IsValid_O_período_máximo_deve_ser_de__0__dia_s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O período mínimo deve ser de {0} dia(s)..
        /// </summary>
        public static string XDateRangeAttribute_IsValid_O_período_mínimo_deve_ser_de__0__dia_s__ {
            get {
                return ResourceManager.GetString("XDateRangeAttribute_IsValid_O_período_mínimo_deve_ser_de__0__dia_s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período informado é inválido..
        /// </summary>
        public static string XDateRangeAttribute_IsValid_Período_informado_é_inválido_ {
            get {
                return ResourceManager.GetString("XDateRangeAttribute_IsValid_Período_informado_é_inválido_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser informado.
        /// </summary>
        public static string XDateTimeAttribute_XDateTimeAttribute_O_campo__0__deve_ser_informado {
            get {
                return ResourceManager.GetString("XDateTimeAttribute_XDateTimeAttribute_O_campo__0__deve_ser_informado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser informado..
        /// </summary>
        public static string XForeignKeyAttribute_XForeignKeyAttribute_O_campo__0__deve_ser_informado_ {
            get {
                return ResourceManager.GetString("XForeignKeyAttribute_XForeignKeyAttribute_O_campo__0__deve_ser_informado_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A imagem associada ao campo {0} não pode ser maior que {1} MB..
        /// </summary>
        public static string XImageAttribute_XImageAttribute_A_imagem_associada_ao_campo__0__não_pode_ser_maior_que__1__MB_ {
            get {
                return ResourceManager.GetString("XImageAttribute_XImageAttribute_A_imagem_associada_ao_campo__0__não_pode_ser_maio" +
                        "r_que__1__MB_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não pode exceder {1} caracter(es)..
        /// </summary>
        public static string XMaxLengthAttribute_Message {
            get {
                return ResourceManager.GetString("XMaxLengthAttribute_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não pode ficar vazio..
        /// </summary>
        public static string XNotEmptyAttribute_XNotEmptyAttribute_O_campo__0__não_pode_ficar_vazio_ {
            get {
                return ResourceManager.GetString("XNotEmptyAttribute_XNotEmptyAttribute_O_campo__0__não_pode_ficar_vazio_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} permite um valor entre {1} e {2}.
        /// </summary>
        public static string XRangeAttribute_CreateErrorMessage_O_campo__0__permite_um_valor_entre__1__e__2_ {
            get {
                return ResourceManager.GetString("XRangeAttribute_CreateErrorMessage_O_campo__0__permite_um_valor_entre__1__e__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} permite um valor máximo {2}.
        /// </summary>
        public static string XRangeAttribute_CreateErrorMessage_O_campo__0__permite_um_valor_máximo__2_ {
            get {
                return ResourceManager.GetString("XRangeAttribute_CreateErrorMessage_O_campo__0__permite_um_valor_máximo__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} permite um valor mínimo {1}.
        /// </summary>
        public static string XRangeAttribute_CreateErrorMessage_O_campo__0__permite_um_valor_mínimo__1_ {
            get {
                return ResourceManager.GetString("XRangeAttribute_CreateErrorMessage_O_campo__0__permite_um_valor_mínimo__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} deve ser informado..
        /// </summary>
        public static string XRequiredAttribute_XRequiredAttribute_O_campo__0__deve_ser_informado_ {
            get {
                return ResourceManager.GetString("XRequiredAttribute_XRequiredAttribute_O_campo__0__deve_ser_informado_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} não possui um RUC válido..
        /// </summary>
        public static string XRucOrCiAttribute_XRucOrCiAttribute_O_campo__0__não_possui_um_RUC_válido_ {
            get {
                return ResourceManager.GetString("XRucOrCiAttribute_XRucOrCiAttribute_O_campo__0__não_possui_um_RUC_válido_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INATIVO.
        /// </summary>
        public static string XTypeDescriptor_Inactive {
            get {
                return ResourceManager.GetString("XTypeDescriptor_Inactive", resourceCulture);
            }
        }
    }
}
