//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetAppBase.Std.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DbEnums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbEnums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetAppBase.Std.Library.Properties.DbEnums", typeof(DbEnums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string EFileExtension_Any {
            get {
                return ResourceManager.GetString("EFileExtension_Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos Csv (Valores Separados por Vírgula) (*.csv).
        /// </summary>
        public static string EFileExtension_Csv {
            get {
                return ResourceManager.GetString("EFileExtension_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento do Word (*.doc).
        /// </summary>
        public static string EFileExtension_Doc {
            get {
                return ResourceManager.GetString("EFileExtension_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento do Word (*.docx).
        /// </summary>
        public static string EFileExtension_Docx {
            get {
                return ResourceManager.GetString("EFileExtension_Docx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos de E-mail (*.eml).
        /// </summary>
        public static string EFileExtension_Eml {
            get {
                return ResourceManager.GetString("EFileExtension_Eml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Múltiplas Extensões.
        /// </summary>
        public static string EFileExtension_MultiExtensions {
            get {
                return ResourceManager.GetString("EFileExtension_MultiExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato de Documento Portável (*.pdf).
        /// </summary>
        public static string EFileExtension_Pdf {
            get {
                return ResourceManager.GetString("EFileExtension_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Portável (*.png).
        /// </summary>
        public static string EFileExtension_Png {
            get {
                return ResourceManager.GetString("EFileExtension_Png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento de Texto (*.txt).
        /// </summary>
        public static string EFileExtension_Txt {
            get {
                return ResourceManager.GetString("EFileExtension_Txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desconhecido.
        /// </summary>
        public static string EFileExtension_Unknown {
            get {
                return ResourceManager.GetString("EFileExtension_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilhas do Excel (*.xls).
        /// </summary>
        public static string EFileExtension_Xls {
            get {
                return ResourceManager.GetString("EFileExtension_Xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planilhas do Excel (*.xlsx).
        /// </summary>
        public static string EFileExtension_Xlsx {
            get {
                return ResourceManager.GetString("EFileExtension_Xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivos de Marcação (*.xml).
        /// </summary>
        public static string EFileExtension_Xml {
            get {
                return ResourceManager.GetString("EFileExtension_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brasil.
        /// </summary>
        public static string EModoOperacao_Brasil {
            get {
                return ResourceManager.GetString("EModoOperacao_Brasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paraguai.
        /// </summary>
        public static string EModoOperacao_Paraguai {
            get {
                return ResourceManager.GetString("EModoOperacao_Paraguai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro.
        /// </summary>
        public static string ETextAlignment_Center {
            get {
                return ResourceManager.GetString("ETextAlignment_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esquerda.
        /// </summary>
        public static string ETextAlignment_Left {
            get {
                return ResourceManager.GetString("ETextAlignment_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direita.
        /// </summary>
        public static string ETextAlignment_Right {
            get {
                return ResourceManager.GetString("ETextAlignment_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string EValidationKind_Error {
            get {
                return ResourceManager.GetString("EValidationKind_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        public static string EValidationKind_Warning {
            get {
                return ResourceManager.GetString("EValidationKind_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período informado é inválido..
        /// </summary>
        public static string XDateRangeAttribute_IsValid_Período_informado_é_inválido_ {
            get {
                return ResourceManager.GetString("XDateRangeAttribute_IsValid_Período_informado_é_inválido_", resourceCulture);
            }
        }
    }
}
